apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: analytics
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  strategy: {}
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - image: 615115875849.dkr.ecr.us-east-1.amazonaws.com/project3:0.0.2
        name: project3
        env:
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: 4J7GhmBgVJ
          - name: DB_HOST
            value: postgre-postgresql
        imagePullPolicy: "Always"